#!/bin/bash
# This is a simple post deploy hook executed after your application 
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.
source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate
export PYTHONPATH=`echo $OPENSHIFT_REPO_DIR`:`echo $OPENSHIFT_REPO_DIR`wsgi:$PYTHONPATH
